### ISSUE TITLE
KeyError: 'completed_tasks'

### ISSUE THREAD

**Issue by yuyang16101066** [clvrai/spirl#1]
I encounter error like this:
Traceback (most recent call last):
  File "spirl/rl/train.py", line 311, in <module>
    RLTrainer(args=get_args())
  File "spirl/rl/train.py", line 76, in __init__
    self.train(start_epoch)
  File "spirl/rl/train.py", line 104, in train
    self.warmup()
  File "spirl/rl/train.py", line 190, in warmup
    warmup_experience_batch, _ = self.sampler.sample_batch(batch_size=self._hp.n_warmup_steps)
  File "/home/user/spirl/spirl/rl/components/sampler.py", line 154, in sample_batch
    obs, reward, done, info = self._env.step(agent_output.action)
  File "/home/user/spirl/spirl/rl/envs/kitchen.py", line 20, in step
    return obs, np.float64(rew), done, self._postprocess_info(info)     # casting reward to float64 is important for getting shape later
  File "/home/user/spirl/spirl/rl/envs/kitchen.py", line 34, in _postprocess_info
    completed_subtasks = info.pop("completed_tasks")
KeyError: 'completed_tasks'

It seems that there is no  'completed_tasks' in info.

**Comment by kpertsch** [comment]
Are you sure that you installed the fork of the D4RL repo from here: https://github.com/kpertsch/d4rl  ?
If you installed the original D4RL repo you would see an error like you posted above since it lacks some small modifications.
In the fork, this line adds the 'completed_task' info: https://github.com/kpertsch/d4rl/blob/b4f66766eb4efe1a86001779db026f1cf4b79d9b/d4rl/kitchen/kitchen_envs.py#L91

**Comment by yuyang16101066** [comment]
> Are you sure that you installed the fork of the D4RL repo from here: https://github.com/kpertsch/d4rl ?
> If you installed the original D4RL repo you would see an error like you posted above since it lacks some small modifications.
> In the fork, this line adds the 'completed_task' info: https://github.com/kpertsch/d4rl/blob/b4f66766eb4efe1a86001779db026f1cf4b79d9b/d4rl/kitchen/kitchen_envs.py#L91

It works, thanks!
