### ISSUE TITLE
RuntimeError: No filenames found in /home/user_name/rl_ws/spirl/data/block_stacking

### ISSUE THREAD

**Issue by yquantao** [clvrai/spirl#11]
Hi,

I downloaded block_stacking.zip dataset and put it in the created folder, like ./data/block_stacking/blocking_stacking.zip, the data_dir is /home/user_name/rl_ws/spirl/data/block_stacking, while the file can not be found, I also tried this way ./data/blocking_stacking.zip, it is the same, did I miss something?

Thanks.

**Comment by kpertsch** [comment]
Hi! 

You need to unpack the zip file before using the data for training. I.e. please unpack block_stacking.zip in the `data/block_stacking` directory and then try to rerun your command, pointing to the unzipped directory in your config's `data_dir`.

I just updated the [data README](https://github.com/clvrai/spirl/blob/master/spirl/data/README.md) to mention this more clearly. Sorry for the confusion!

**Comment by yquantao** [comment]
Hi,

thank you for your reply and it works now, I have one more question about kitchen dataset. As described kitchen dataset is downloaded automatically, where is the default directory if it is stored locally? I didn't find the local kitchen dataset in data_dir.

**Comment by kpertsch** [comment]
For the kitchen dataset we are relying on D4RL's dataset download functionality. From scanning [their code](https://github.com/kpertsch/d4rl/blob/88dbee5fe898247a4a41b47e21783b15dae24916/d4rl/offline_env.py#L11) it seems that by default it gets stored into `~/.d4rl/datasets`, but you should be able to change that by setting the `D4RL_DATASET_DIR` environment variable.

**Comment by yquantao** [comment]
Thank you again for your help!
