### ISSUE TITLE
RuntimeError of gradient compuptation

### ISSUE THREAD

**Issue by rainbow979** [clvrai/spirl#15]
Hi, I added a new RL environment and run as readme.md. But I met this issue when `self._perform_update(policy_loss, self.policy_opt, self.policy)`:

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

Could you offer some help?

**Comment by rainbow979** [comment]
I found answer in https://github.com/clvrai/spirl/issues/6#issuecomment-822339076. I wonder whether the movement influenced the result?

**Comment by kpertsch** [comment]
Hi! I am glad you found the fix! 

In our implementation of SAC swapping the order of policy and critic update should not change the result of training since all the losses are computed before the updates are performed, so the order of updates does not change the outcome.

**Comment by rainbow979** [comment]
OK. Thanks
