### ISSUE TITLE
How to regenerate kitchen dataset?

### ISSUE THREAD

**Issue by yquantao** [clvrai/spirl#19]
Hi,

do we have a way to regenerate new datasets for the kitchen environment?

**Comment by kpertsch** [comment]
Hi!

For the experiments in the kitchen environment we have relied on the dataset published in "Relay Policy Learning" (Gupta et al., 2019). This dataset was collected using human teleoperation and the published code does not include the teleop interface, thus there is currently no easy way to generate more data in the kitchen environment. 

You could try to train expert policies for every of the 7 subtasks in the kitchen (opening microwave, turning on stove etc) using the expert sequences from the dataset and then chain these primitive policies to solve new combinations of subtasks, but it would probably need some engineering to get to work & likely not deliver the same quality of expert demonstrations the current dataset has.

**Comment by yquantao** [comment]
Thanks a lot for this info!
