### ISSUE TITLE
Could not find calibration file 

### ISSUE THREAD

**Issue by lnj0532** [clvrai/spirl#2]
Thank you for sharing codes.

when  I run " python3 spirl/train.py --path=spirl/configs/skill_prior_learning/kitchen/flat --val_data_size=160 "

I encounter error like this:
"
Could not find calibration file at: /d4rl/kitchen/adept_envs/franka/robot/franka_config.xml
"
how can I solve this problem

**Comment by kpertsch** [comment]
I have not encountered this problem. The file in question exists in the D4RL repo so I am not sure why it is not found: https://github.com/kpertsch/d4rl/blob/master/d4rl/kitchen/adept_envs/franka/robot/franka_config.xml

As a first step, can you make sure that you installed [my fork of the D4RL repo](https://github.com/kpertsch/d4rl) (not the original repo) and that you actually installed it with `pip3 install -e .` while inside the D4RL repo.

If the problem persists maybe you can also print the full error stack to make debugging easier.

**Comment by lnj0532** [comment]
Thanks for your immediately replay.  I solved this problem  by downloading the franka_config.xml  and copy it to robot folder.
