### ISSUE TITLE
completed_subtasks = info.pop("computed_tasks error")

### ISSUE THREAD

**Issue by gd-goblin** [clvrai/spirl#21]
Hello, I have an issue on the SPiRL learning. 

After I finished the skill prior learning on the kitchen environment, 
I tried to train the SPiRL_CL based on the skill prior network. 

But I got the KeyError when my code attempts pop the key "completed_tasks" from info variable

![image](https://user-images.githubusercontent.com/25500255/154651079-cff932e5-0419-4be5-9650-0f3ba5b5149f.png)

I don't understand the code line 33 of __postprocess_info_ because the returned "info" from _step_ function only contains the following 5 key-value pairs as described in "kitchen_multitask_v0.py"

![image](https://user-images.githubusercontent.com/25500255/154652153-59bcf2bd-7a8d-4d1b-9b8d-c29afda91b2a.png)

and, I could not find any other parts of adding the "completed_tasks" key to the info variable. 

Am I missing something?

**Comment by gd-goblin** [comment]
Sorry, I didn't check the same, but already closed issue. 
Now it works! and plz delete this issue.

Thanks anyway :)

**Comment by kpertsch** [comment]
Yes -- you need to install our fork of D4RL since we added a few info outputs to the env (to log subtask completion rates separately). Anyways, glad it works now, let me know if you have any other issues / questions! :)
