### ISSUE TITLE
How can i simulate the trained policy for kitchen environment with Mujoco or another?

### ISSUE THREAD

**Issue by whiteBerryJ** [clvrai/spirl#23]
Hi.

I trained the skill prior and hrl with example commands ('kitchen-mixed-v0').
How can i simulate the trained policy for kitchen environment with Mujoco? (like this https://clvrai.github.io/spirl/)

**Comment by kpertsch** [comment]
Hi!

The code automatically logs videos to WandB during the evaluation step (if rendering was not disabled). You should be able to find the videos on WandB after the first evaluation cycle was run and also download them from there!
