### ISSUE TITLE
Is it possible to change the camera zoom?

### ISSUE THREAD

**Issue by jsw7460** [clvrai/spirl#28]
Thank you for your great work. 

I understand the given dataset and generating process focuses on agent's current location, but
I want to create an image based 2d maze dataset where entire map is given (zoomed out).
 
Where can i start for this?
Thanks!

**Comment by kpertsch** [comment]
Hey!

This is pretty easy! You can add a "birdview" camera by uncommenting one of the lines in the model definition [here](https://github.com/kpertsch/d4rl/blob/a4e37c6a9469a7dbf8849496e0ba4f912f921cb3/d4rl/pointmaze/maze_model.py#L85). Then you can render frames from this camera by adding the `camera_name` argument to the render function:
```
img = env.render(mode='rgb_array', camera_name='birdview')
```

You might need to play around with the position parameters for the camera a little bit depending on the size of the maze you are using, but should be easy to figure out in a few trials!
