### ISSUE TITLE
regularization in the first stage

### ISSUE THREAD

**Issue by han-x** [clvrai/spirl#9]
In Sec 3.2, equation 1. wants to maximize the following evidence lower bound (ELBO): 
E_q[ log p(a_i|z ) - \beta (log q(z|a_i) - logp(z)) ], 

 But in  Sec B. the equation t. want to minimize the regulation loss 
 - \beta D_KL ( N(m_z, std_z) ||  N(0 , 1) )

So the algorithm wants to make the KL divergence between Skill Posterior q(z|a_i) and Fixed Prior N(0, 1) larger or smaller?
This question has bothered me for days, if you can reply to me, I will be very grateful!

**Comment by kpertsch** [comment]
That's indeed a typo in the appendix. Our goal is to minimize the divergence between skill posterior and fixed prior to regularize the learned representation and end up with a smoother manifold. So the ELBO expression in Sec 3.2 is correct but the sign in front of the KL divergence in Sec B should be a "+" (assuming that \beta > 0). 

You can also see that we are minimizing KL divergence in the code [here](https://github.com/clvrai/spirl/blob/c39f8869b8248e35582aa64fb848e4d89b3d45ee/spirl/models/skill_prior_mdl.py#L142).

**Comment by han-x** [comment]
Thanks for your reply, it is very helpful to me! 
By the way, this work is very enlightening, especially the use of skill prior and modified maximum entropy algorithm with skill prior which gives me lots of inspiration.
